
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x20000, LENGTH = 0x0020000
}
ENTRY(_main_init)
SECTIONS
{
  . = 0x0;
  .text : { 
     // the _main_init symbol from me_basic.o has to come at address zero.
     *me_basic.o(.text)
     . = 0x200;
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text)
  } > program
  .data : { 
     *(.data*);
     *(.rodata*)
  } > data
  . = 0x20000;
  _sp_start_value_DM_stack = .;
  . = 0x24000;
. = 0x29000;
buf5 = .;
. += 0x1000;
. = 0x2A000;
buf6 = .;
. += 0x1000;
. = 0x2B000;
buf7 = .;
. += 0x1000;
. = 0x2C000;
buf8 = .;
. += 0x1000;
. = 0x31000;
buf9 = .;
. += 0x1000;
. = 0x32000;
buf10 = .;
. += 0x1000;
. = 0x33000;
buf11 = .;
. += 0x1000;
  .bss : { *(.bss) } > data
  .bss.DMb.4 : { *(.bss.DMb.4) } > data
}
INPUT(kernel.o)
